@once
<style>
.ffp-panel{--ffp-line:#e2e8f0;--ffp-muted:#64748b;--ffp-soft:#f8fafc;--ffp-bg:#fff;--ffp-text:#0f172a;color:var(--ffp-text)}
.dark .ffp-panel{--ffp-line:#334155;--ffp-muted:#94a3b8;--ffp-soft:#1e293b;--ffp-bg:#111827;--ffp-text:#f1f5f9}
.ffp-muted{color:var(--ffp-muted);font-size:.875rem}.ffp-stack{display:grid;gap:1rem}.ffp-card{border:1px solid var(--ffp-line);border-radius:14px;background:var(--ffp-bg);overflow:hidden}.ffp-pad{padding:1.25rem}.ffp-row{display:flex;align-items:center;gap:.75rem;flex-wrap:wrap}.ffp-between{justify-content:space-between}.ffp-heading{font-size:1rem;font-weight:650}.ffp-url{overflow-wrap:anywhere;font-size:.8rem;color:var(--ffp-muted)}
.ffp-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.ffp-number{font-size:2rem;font-weight:650;line-height:1.3;margin-top:.5rem}.ffp-icon{width:20px;height:20px;flex-shrink:0}.ffp-table-wrap{overflow-x:auto}.ffp-table{width:100%;border-collapse:collapse;text-align:left;font-size:.875rem}.ffp-table th{background:var(--ffp-soft);color:var(--ffp-muted);font-size:.75rem;letter-spacing:.04em;text-transform:uppercase;padding:1rem;white-space:nowrap}.ffp-table td{padding:1rem;border-top:1px solid var(--ffp-line);vertical-align:middle}.ffp-table tbody tr:hover{background:var(--ffp-soft)}.ffp-table tr[aria-selected=true]{background:var(--ffp-soft);box-shadow:inset 3px 0 #6366f1}.ffp-subject{min-width:220px;max-width:400px}.ffp-empty{text-align:center;padding:2.5rem;color:var(--ffp-muted)}.ffp-notice{padding:.85rem 1rem;border-radius:10px;background:var(--ffp-soft);font-size:.875rem}.ffp-date{border:1px solid var(--ffp-line);border-radius:8px;padding:.5rem .75rem;background:var(--ffp-bg);color:inherit;color-scheme:light}.dark .ffp-date{color-scheme:dark}
.ffp-performance{display:grid;grid-template-columns:210px 1fr;gap:2rem;padding:1.5rem;border-top:1px solid var(--ffp-line)}.ffp-gauge{position:relative;width:128px;height:128px;margin:0 auto .5rem}.ffp-gauge svg{width:128px;height:128px;transform:rotate(-90deg)}.ffp-gauge-value{position:absolute;inset:0;display:grid;place-items:center;font-size:2.5rem;font-weight:600;font-variant-numeric:tabular-nums}.ffp-score{text-align:center}.ffp-legend{display:flex;gap:1rem;justify-content:center;margin-top:1rem;font-size:.75rem;color:var(--ffp-muted)}.ffp-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:4px}.ffp-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.ffp-metric{padding:.75rem 0;border-bottom:1px solid var(--ffp-line)}.ffp-metric dd{font-size:1.6rem;margin-top:.3rem;font-variant-numeric:tabular-nums}.ffp-section{border-top:1px solid var(--ffp-line);padding:1.25rem}.ffp-section summary{cursor:pointer;font-weight:600}.ffp-findings{margin-top:1rem;display:grid;gap:.75rem}.ffp-finding{padding:.85rem;background:var(--ffp-soft);border-radius:8px}.ffp-prose{line-height:1.75}.ffp-prose p{margin:.75rem 0}.ffp-prose ul{list-style:disc;padding-left:1.5rem}.ffp-prose ol{list-style:decimal;padding-left:1.5rem}
@media(max-width:700px){.ffp-stats{grid-template-columns:1fr}.ffp-performance{grid-template-columns:1fr;gap:1rem}.ffp-metrics{gap:.75rem}.ffp-pad{padding:1rem}}
</style>
@endonce
